import {normalizePackage,STORAGE_KEY} from '../shared/schema.js';
const $=s=>document.querySelector(s);let current=null;let page={isListingPage:false};
const isSupportedListing=url=>/^https:\/\/www\.etsy\.com\/(?:your\/shops\/[^/]+\/(?:listing-editor\/(?:create|edit)|(?:tools\/)?listings?\/(?:create|edit))|listing\/\d+\/edit)/i.test(url||'');
async function connectToListing(tab){
  if(tab?.id&&isSupportedListing(tab.url))await chrome.scripting.executeScript({target:{tabId:tab.id},world:'MAIN',files:['content/etsy-main.js']}).catch(()=>{});
  try{return await chrome.tabs.sendMessage(tab.id,{type:'SHOPMINT_PING'})}catch(error){
    if(!tab?.id||!isSupportedListing(tab.url))throw error;
    await chrome.scripting.insertCSS({target:{tabId:tab.id},files:['content/panel.css']}).catch(()=>{});
    await chrome.scripting.executeScript({target:{tabId:tab.id},files:['content/etsy-map.js','content/content.js']});
    return chrome.tabs.sendMessage(tab.id,{type:'SHOPMINT_PING'});
  }
}
const views={empty:$('#empty'),ready:$('#ready'),report:$('#report')};
function show(name){Object.entries(views).forEach(([k,v])=>v.classList.toggle('hidden',k!==name))}
function toast(message,error=false){const el=$('#toast');el.textContent=message;el.className=error?'show error':'show';setTimeout(()=>el.className='',2400)}
async function detect(){const [tab]=await chrome.tabs.query({active:true,currentWindow:true});try{const result=await connectToListing(tab);page=result||{};$('#pageStatus').textContent=page.isListingPage?'Etsy listing detected':'Open an Etsy listing';$('#pageStatus').className=`page-pill ${page.isListingPage?'found':'waiting'}`}catch{page={isListingPage:false};$('#pageStatus').textContent=isSupportedListing(tab?.url)?'Reload Sidekick extension':'Open an Etsy listing';$('#pageStatus').className='page-pill waiting'}updateFill()}
function updateFill(){const b=$('#fill');if(!b)return;b.disabled=!page.isListingPage;b.title=page.isListingPage?'':'Open an Etsy listing creation or edit page first'}
function render(pkg){current=pkg;show('ready');$('#productType').textContent=pkg.productType;$('#productName').textContent=pkg.productName;$('#packageMeta').textContent=`Package v${pkg.schemaVersion} · ${new Date(pkg.updatedAt||Date.now()).toLocaleDateString()}`;$('#titlePreview').textContent=pkg.title;$('#pricePreview').textContent=`$${Number(pkg.price).toFixed(2)}`;$('#tagCount').textContent=`${pkg.tags.length}/13`;$('#categoryNote').innerHTML=`<b>Category · manual selection</b><span>${pkg.categorySuggestion||'Choose the best matching Etsy category'}</span>`;$('#imageCount').textContent=String(pkg.mockupImages?.length||pkg.imageChecklist?.length||pkg.mockups?.length||0);$('#fileCount').textContent=String(pkg.deliveryChecklist?.length||pkg.sourceFiles?.filter(x=>x.customerFile).length||0);updateFill()}
async function loadFile(file){try{const pkg=normalizePackage(JSON.parse(await file.text()));await chrome.storage.local.set({[STORAGE_KEY]:pkg});render(pkg);toast('Package ready')}catch(error){toast(error.message||'Could not read this package',true)}}
$('#fileInput').addEventListener('change',e=>e.target.files[0]&&loadFile(e.target.files[0]));
$('#removePackage').onclick=async()=>{await chrome.storage.local.remove(STORAGE_KEY);current=null;show('empty');toast('Package removed')};
$('#fill').onclick=async()=>{if(!current)return;const button=$('#fill');button.disabled=true;button.innerHTML='FILLING TEXT & TAGS…';try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});const mode=document.querySelector('input[name="mode"]:checked').value;const {mockupImages=[], ...listingPackage}=current;const report=await chrome.tabs.sendMessage(tab.id,{type:'SHOPMINT_FILL',package:listingPackage,mode});if(!report?.ok)throw new Error(report?.error||'The page could not be filled.');if(mode==='all')report.results.push({field:'listingImages',status:'manual',reason:`MANUAL REVIEW REQUIRED — In Etsy Photo & Video, click Upload and select all ${mockupImages.length||current.imageChecklist?.length||0} exported mockups together.`});renderReport(report)}catch(error){toast(error.message||'Etsy did not respond. Refresh the page and try again.',true)}finally{button.innerHTML='FILL MY LISTING <span>→</span>';updateFill()}};
function renderReport(report){show('report');const filled=report.results.filter(x=>x.status==='filled').length;$('#reportTitle').textContent=filled?`${filled} fields filled.`:'Manual review needed.';$('#reportSubtitle').textContent=`${current.productName} · ${new Date(report.at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}`;const labels={filled:'Filled',needsReview:'Needs review',manual:'MANUAL REVIEW REQUIRED',notFound:'Not found',skipped:'Skipped',error:'Error'};$('#reportGroups').innerHTML=Object.entries(labels).map(([status,label])=>{const rows=report.results.filter(x=>x.status===status);return rows.length?`<div class="report-group ${status}"><h3>${label}<span>${rows.length}</span></h3>${rows.map(x=>`<div><b>${pretty(x.field)}</b><small>${escapeHtml(x.reason||'')}</small></div>`).join('')}</div>`:''}).join('')}
const pretty=s=>s.replace(/([A-Z])/g,' $1').replace(/^./,x=>x.toUpperCase());const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
$('#backToReady').onclick=()=>render(current);$('#demoInvalid').onclick=()=>toast('Choose a SHOPMINT listing JSON export (v1.0, v1.1, or v1.2).');
document.querySelectorAll('[data-copy]').forEach(button=>button.onclick=async()=>{const key=button.dataset.copy;const value=key==='tags'?current.tags.join(', '):String(current[key]??'');await navigator.clipboard.writeText(value);toast(`${pretty(key)} copied`)});
chrome.storage.local.get(STORAGE_KEY).then(value=>{if(value[STORAGE_KEY]){try{render(normalizePackage(value[STORAGE_KEY]))}catch{show('empty')}}else show('empty')});detect();
