(()=>{
  const config=globalThis.ShopmintSidekick.etsy;
  const state={lastReport:null,minimized:false};
  const clean=s=>String(s??'').trim();
  const isVisible=el=>!!(el&&el.isConnected&&(el.offsetWidth||el.offsetHeight||el.getClientRects().length)&&!el.disabled);
  function isListingPage(){return config.listingUrlPatterns.some(p=>p.test(location.href));}
  function byLabel(labels){for(const text of labels){const label=[...document.querySelectorAll('label')].find(x=>clean(x.textContent).toLowerCase().includes(text.toLowerCase()));if(label){const id=label.getAttribute('for');const target=id&&document.getElementById(id);if(isVisible(target))return target;const nested=label.querySelector('input,textarea,select,[contenteditable="true"]');if(isVisible(nested))return nested}const aria=[...document.querySelectorAll('input,textarea,select,[contenteditable="true"]')].find(x=>clean(x.getAttribute('aria-label')).toLowerCase().includes(text.toLowerCase()));if(isVisible(aria))return aria}return null}
  function findField(def){for(const selector of def.selectors){const el=[...document.querySelectorAll(selector)].find(isVisible);if(el)return el}return byLabel(def.labels)}
  function nativeSet(el,value){el.focus();if(el instanceof HTMLSelectElement){el.value=value;el.dispatchEvent(new Event('change',{bubbles:true}))}else if(el.isContentEditable){el.textContent=value;el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:value}))}else{const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;setter?.call(el,String(value));el.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:String(value)}));el.dispatchEvent(new Event('change',{bubbles:true}))}el.dispatchEvent(new FocusEvent('blur',{bubbles:true}));return clean(el.value??el.textContent)===clean(value)}
  async function fillField(key,value){if(value===undefined||value===null||clean(value)==='')return{field:key,status:'skipped',reason:'No package value'};const def=config.fields[key];if(!def)return{field:key,status:'manual',reason:'No safe mapping'};let el=findField(def);if(!el&&def.revealLabels){const button=[...document.querySelectorAll('button')].find(x=>isVisible(x)&&def.revealLabels.some(label=>clean(x.textContent).toLowerCase()===label.toLowerCase()));if(button){button.click();await new Promise(r=>setTimeout(r,180));el=findField(def)}}if(!el)return{field:key,status:'notFound',reason:'Field not found'};try{const verified=nativeSet(el,value);await new Promise(r=>setTimeout(r,120));const after=clean(el.value??el.textContent);return{field:key,status:verified||after===clean(value)?'filled':'needsReview',reason:verified?'Verified':'Page did not confirm the value'}}catch{return{field:key,status:'error',reason:'Field rejected the value'}}}
  function creationGroup(question){return[...document.querySelectorAll('fieldset,[role="group"]')].find(group=>clean(group.textContent).toLowerCase().includes(question.toLowerCase()))||null}
  async function fillCreationRadio(key,value){const def=config.creation[key];const answer=def?.answers?.[value];if(!answer)return{field:key,status:'manual',reason:`MANUAL REVIEW REQUIRED — No SHOPMINT answer selected`};const group=creationGroup(def.question);if(!group)return{field:key,status:'manual',reason:`MANUAL REVIEW REQUIRED — Etsy control not found. Selected in SHOPMINT: ${answer}`};const radio=[...group.querySelectorAll('input[type="radio"]')].find(input=>{const label=input.closest('label')||(input.id&&document.querySelector(`label[for="${input.id}"]`));return clean(label?.textContent).toLowerCase().includes(answer.toLowerCase())});if(!radio)return{field:key,status:'manual',reason:`MANUAL REVIEW REQUIRED — Etsy option not found. Selected in SHOPMINT: ${answer}`};try{radio.click();radio.dispatchEvent(new Event('change',{bubbles:true}));await new Promise(r=>setTimeout(r,180));const accepted=radio.checked||radio.getAttribute('aria-checked')==='true';return{field:key,status:accepted?'filled':'needsReview',reason:accepted?`Verified: ${answer}`:`MANUAL REVIEW REQUIRED — Etsy did not confirm: ${answer}`}}catch{return{field:key,status:'error',reason:`MANUAL REVIEW REQUIRED — Etsy rejected: ${answer}`}}}
  async function fillCreation(details){const results=[];if(!details){return['whoMade','whatIsIt','digitalCreation','productionPartner'].map(field=>({field,status:'manual',reason:'MANUAL REVIEW REQUIRED — Creation detail missing from this package'}))}for(const key of ['whoMade','whatIsIt','digitalCreation'])results.push(await fillCreationRadio(key,details[key]));const partnerAnswer=details.productionPartner==='none'?'No production partner':details.productionPartner==='uses-production-partner'?`Uses a production partner${details.productionPartnerName?`: ${details.productionPartnerName}`:''}`:'Not answered';results.push({field:'productionPartner',status:'manual',reason:`MANUAL REVIEW REQUIRED — Selected in SHOPMINT: ${partnerAnswer}. Confirm or select this in Etsy.`});if(details.whenMade&&details.whenMade!=='not-applicable-digital')results.push({field:'whenMade',status:'manual',reason:`MANUAL REVIEW REQUIRED — Selected in SHOPMINT: ${details.whenMade}`});return results}
  function tagContainer(){const input=config.tags.inputSelectors.flatMap(s=>[...document.querySelectorAll(s)]).find(el=>el.isConnected);return input?.closest('fieldset,[role="group"],section')||config.tags.containerSelectors.map(s=>document.querySelector(s)).find(Boolean)||null}
  function currentTags(){const container=tagContainer();if(!container)return[];return [...container.querySelectorAll('[data-tag],li')].map(x=>clean(x.textContent).replace(/remove/ig,'')).filter(x=>x&&x.length<=30)}
  async function fillTags(tags){const unique=[...new Set(tags.map(clean).filter(Boolean).map(x=>x.toLowerCase()))].slice(0,13);const entered=[],failed=[];for(let index=0;index<unique.length;index++){const lower=unique[index];if(currentTags().some(t=>t.toLowerCase()===lower)){entered.push(lower);continue}const input=config.tags.inputSelectors.flatMap(s=>[...document.querySelectorAll(s)]).find(isVisible);if(!input){failed.push(...unique.slice(index));break}input.focus();nativeSet(input,lower);input.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',bubbles:true}));input.dispatchEvent(new KeyboardEvent('keyup',{key:'Enter',code:'Enter',bubbles:true}));await new Promise(r=>setTimeout(r,220));const recognized=currentTags().some(t=>t.toLowerCase()===lower)||clean(input.value)==='';if(recognized)entered.push(lower);else failed.push(lower)}return{field:'tags',status:failed.length?'needsReview':'filled',reason:failed.length?`${entered.length} added; ${failed.length} could not be verified`:`${entered.length} unique tags added`,entered,failed}}
  async function runFill(pkg,mode){if(!isListingPage())return{ok:false,error:'Open an Etsy listing create or edit page first.'};const results=[];if(mode!=='tags'){for(const key of ['title','description','price','quantity','sku'])results.push(await fillField(key,pkg[key]));if(mode==='all'){for(const key of ['materials','primaryColor','secondaryColor','occasion','holiday','personalization'])results.push(await fillField(key,pkg[key]));results.push(...await fillCreation(pkg.creationDetails))}}if(mode!=='text')results.push(await fillTags(pkg.tags||[]));results.push({field:'category',status:'manual',reason:pkg.categorySuggestion?`Select manually: ${pkg.categorySuggestion}`:'Select a category manually'});results.push({field:'listingImages',status:'manual',reason:'Browser security requires manual file selection'});results.push({field:'digitalFiles',status:'manual',reason:'Browser security requires manual file selection'});const report={ok:true,at:new Date().toISOString(),productName:pkg.productName,mode,results};state.lastReport=report;showPanel(pkg,report);return report}
  function showPanel(pkg,report){let root=document.getElementById('shopmint-sidekick-panel');if(!root){root=document.createElement('aside');root.id='shopmint-sidekick-panel';document.body.append(root)}const filled=report.results.filter(x=>x.status==='filled').length;const remaining=report.results.length-filled;root.innerHTML=`<button class="sm-min" aria-label="Minimize SHOPMINT SIDEKICK">${state.minimized?'S':'−'}</button><div class="sm-body"><span>SHOPMINT™ SIDEKICK</span><strong>${escapeHtml(pkg.productName)}</strong><div><b>${filled}</b> filled · <b>${remaining}</b> to review</div><small>Review every field. SIDEKICK never publishes.</small></div>`;root.classList.toggle('sm-collapsed',state.minimized);root.querySelector('.sm-min').onclick=()=>{state.minimized=!state.minimized;showPanel(pkg,report)}}
  const escapeHtml=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message?.type==='SHOPMINT_PING'){sendResponse({ok:true,isEtsy:true,isListingPage:isListingPage(),url:location.href});return}if(message?.type==='SHOPMINT_FILL'){runFill(message.package,message.mode||'all').then(sendResponse);return true}if(message?.type==='SHOPMINT_REPORT'){sendResponse(state.lastReport);return}});
})();
