import {Bot,Check,CircleAlert,Factory,UserRound} from 'lucide-react';
import type {CreationDetails as Details,Project,Settings} from './types';

export const emptyCreationDetails:Details={whoMade:'',whatIsIt:'',digitalCreation:'',productionPartner:'',productionPartnerName:'',whenMade:''};
const whoMade=[['i-did','I did'],['shop-member','A member of my shop'],['another-company-person','Another company or person']] as const;
const whatIsIt=[['finished-product','A finished product'],['supply-tool','A supply or tool to make things']] as const;
const digitalCreation=[['created-by-me','Created by me','It’s designed and created entirely by me.'],['ai-generator','With an AI generator','It’s created with help from an AI generator.']] as const;
const madePeriods=['Made To Order','2020 - 2026','2010 - 2019','2007 - 2009','Before 2007','2000 - 2006','1990s','1980s','1970s','1960s','1950s','1940s','1930s','1920s','1910s','1900 - 1909'] as const;
const currentMade=(value:string)=>value==='not-applicable-digital'?'':value;

export function CreationDetailsPanel({project,update}:{project:Project;update:(f:(p:Project)=>Project)=>void}){
  const value={...emptyCreationDetails,...project.listing.creationDetails};
  const madeValue=currentMade(value.whenMade);
  const set=(key:keyof Details,next:string)=>update(p=>({...p,listing:{...p.listing,creationDetails:{...emptyCreationDetails,...p.listing.creationDetails,[key]:next}}}));
  const missing=!value.whoMade||!value.whatIsIt||!value.digitalCreation||!value.productionPartner||!madeValue;
  return <section className="panel creation-panel"><div className="panel-head"><div><div className="eyebrow">ETSY / HOW IT’S MADE</div><h2>Creation details</h2><p>Current Etsy-compatible answers, verified against the live listing editor.</p></div><div className={missing?'creation-status missing':'creation-status complete'}>{missing?<CircleAlert/>:<Check/>}{missing?'Required answers missing':'Complete'}</div></div>
    {missing&&<div className="migration-note"><CircleAlert/><span><b>Creation details required</b>Answer every current Etsy creation question before exporting to Sidekick.</span></div>}
    <div className="creation-grid"><fieldset><legend><UserRound/> Who made it? <em>Required</em></legend>{whoMade.map(([id,label])=><label key={id}><input type="radio" name={`who-${project.id}`} checked={value.whoMade===id} onChange={()=>set('whoMade',id)}/><span>{label}</span></label>)}</fieldset>
      <fieldset><legend><Factory/> What is it? <em>Required</em></legend>{whatIsIt.map(([id,label])=><label key={id}><input type="radio" name={`what-${project.id}`} checked={value.whatIsIt===id} onChange={()=>set('whatIsIt',id)}/><span>{label}</span></label>)}</fieldset>
      <fieldset className="ai-question"><legend><Bot/> How is this digital content created? <em>Required</em></legend>{digitalCreation.map(([id,label,note])=><label key={id}><input type="radio" name={`ai-${project.id}`} checked={value.digitalCreation===id} onChange={()=>set('digitalCreation',id)}/><span><b>{label}</b><small>{note}</small></span></label>)}<div className="ai-boundary"><b>PRODUCT ARTWORK ≠ MARKETING PRESENTATION</b><p>Answer for the artwork or digital product being sold. SHOPMINT mockup backgrounds do not make the product AI-generated.</p></div></fieldset>
      <fieldset><legend>Production and date <em>Required</em></legend><p className="field-help">A production partner is someone outside your shop who physically produces the item.</p><label><input type="radio" name={`partner-${project.id}`} checked={value.productionPartner==='none'} onChange={()=>set('productionPartner','none')}/><span>No production partner</span></label><label><input type="radio" name={`partner-${project.id}`} checked={value.productionPartner==='uses-production-partner'} onChange={()=>set('productionPartner','uses-production-partner')}/><span>Uses a production partner</span></label>{value.productionPartner==='uses-production-partner'&&<label className="partner-name">Partner name / reminder<input value={value.productionPartnerName} onChange={e=>set('productionPartnerName',e.target.value)} placeholder="Exact partner to select in Etsy"/></label>}<label className="partner-name">When was it made?<select value={madeValue} onChange={e=>set('whenMade',e.target.value)}><option value="">Select Etsy answer</option>{madePeriods.map(period=><option key={period}>{period}</option>)}</select></label></fieldset></div>
  </section>;
}

export function CreationDefaultsPanel({value,change}:{value:Settings;change:(s:Settings)=>void}){
  const details={...emptyCreationDetails,...value.creationDefaults};
  const set=(key:keyof Details,next:string)=>{if(key==='digitalCreation')return;change({...value,creationDefaults:{...value.creationDefaults,[key]:next}})};
  return <section className="creation-defaults"><h2>Etsy creation defaults</h2><p>Applied to new products. AI disclosure is intentionally never defaulted.</p><div className="two"><label>Default “Who made it?”<select value={details.whoMade} onChange={e=>set('whoMade',e.target.value)}><option value="">Ask for each product</option>{whoMade.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Default “What is it?”<select value={details.whatIsIt} onChange={e=>set('whatIsIt',e.target.value)}><option value="">Ask for each product</option>{whatIsIt.map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>Production partner default<select value={details.productionPartner} onChange={e=>set('productionPartner',e.target.value)}><option value="">Ask for each product</option><option value="none">No production partner</option><option value="uses-production-partner">Uses a production partner</option></select></label><label>Default “When was it made?”<select value={currentMade(details.whenMade)} onChange={e=>set('whenMade',e.target.value)}><option value="">Ask for each product</option>{madePeriods.map(period=><option key={period}>{period}</option>)}</select></label><label>Partner reminder<input value={details.productionPartnerName} onChange={e=>set('productionPartnerName',e.target.value)} placeholder="Optional"/></label></div><div className="no-ai-default"><Bot/><span><b>No AI default</b>Every product must explicitly answer Etsy’s AI-generation question.</span></div></section>;
}
