import {useRef,useState} from 'react';
import {ArrowDown,ArrowRight,ArrowUp,Check,CloudDownload,FileArchive,FolderOpen,Image as ImageIcon,LoaderCircle,Star,Trash2} from 'lucide-react';
import type {SourceFile} from './types';
import {fileSize} from './lib';
import {filesFromDirectory,importProductFiles,type ProductImport} from './fileImport';

type Props={files:SourceFile[];onChange:(files:SourceFile[])=>void;onFolderName?:(name:string)=>void;notify:(message:string)=>void;onContinue?:()=>void};
export default function FolderImport({files,onChange,onFolderName,notify,onContinue}:Props){
  const directoryInput=useRef<HTMLInputElement>(null);const looseInput=useRef<HTMLInputElement>(null);const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<Set<string>>(new Set());const [driveUrl,setDriveUrl]=useState('');const [summary,setSummary]=useState<ProductImport>();
  const ordered=[...files].sort((a,b)=>(a.order??999)-(b.order??999));
  const apply=async(input:File[]|FileList,name?:string)=>{setBusy(true);try{const imported=await importProductFiles(input,name);const merged=[...files,...imported.files].map((file,index)=>({...file,order:index,primary:false}));const primary=merged.find(file=>file.type.startsWith('image/'));if(primary)primary.primary=true;onChange(merged);onFolderName?.(imported.folderName);setSummary(imported);notify(`${imported.files.length} supported file${imported.files.length===1?'':'s'} imported from ${imported.folderName}`)}finally{setBusy(false)}};
  const chooseFolder=async()=>{const picker=(window as any).showDirectoryPicker;if(picker){try{const handle=await picker({mode:'read'});await apply(await filesFromDirectory(handle),handle.name);return}catch(error:any){if(error?.name==='AbortError')return}}directoryInput.current?.click()};
  const removeSelected=()=>{const next=files.filter(file=>!selected.has(file.id));const normalized=next.map((file,index)=>({...file,order:index,primary:file.primary}));if(!normalized.some(file=>file.primary)){const first=normalized.find(file=>file.type.startsWith('image/'));if(first)first.primary=true}onChange(normalized);setSelected(new Set())};
  const remove=(id:string)=>{const next=files.filter(file=>file.id!==id).map((file,index)=>({...file,order:index}));if(!next.some(file=>file.primary)){const first=next.find(file=>file.type.startsWith('image/'));if(first)first.primary=true}onChange(next)};
  const move=(id:string,delta:number)=>{const next=[...ordered];const index=next.findIndex(file=>file.id===id),target=Math.max(0,Math.min(next.length-1,index+delta));if(index===target)return;[next[index],next[target]]=[next[target],next[index]];onChange(next.map((file,order)=>({...file,order})))};
  const setPrimary=(id:string)=>onChange(files.map(file=>({...file,primary:file.id===id})));
  return <div className="folder-import"><div className="import-choice"><div><span>FASTEST IMPORT</span><h3>Bring in the whole product folder</h3><p>SHOPMINT reads supported files together, ignores system clutter, and preserves every original filename.</p></div><button className="primary folder-button" onClick={chooseFolder} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<FolderOpen/>} Import product folder</button><input ref={directoryInput} type="file" multiple hidden {...({webkitdirectory:'',directory:''} as any)} onChange={e=>e.target.files&&apply(e.target.files)}/></div>
    <div className="drive-import"><CloudDownload/><div><b>Google Drive folder</b><p>Direct Drive links require Google authorization that this local-only app does not request. Download the folder from Drive, then import the folder or its ZIP here in one action.</p><input aria-label="Google Drive folder link" value={driveUrl} onChange={e=>setDriveUrl(e.target.value)} placeholder="Paste a Drive folder link for guidance"/>{driveUrl&&<small><Check/> Link recognized. In Google Drive choose <b>Download</b>, then use the button below.</small>}</div><button className="secondary" onClick={chooseFolder}>Import downloaded folder</button><button className="secondary" onClick={()=>looseInput.current?.click()}><FileArchive/> Choose Drive ZIP</button><input ref={looseInput} hidden type="file" accept=".zip,.png,.jpg,.jpeg,.webp,.pdf" multiple onChange={e=>e.target.files&&apply(e.target.files,'Google Drive download')}/></div>
    {summary&&<div className="detection-banner"><div><b>{summary.pngCount||summary.imageCount} design{(summary.pngCount||summary.imageCount)===1?'':'s'} detected</b><span>{summary.pngCount>1?'Suggested Product Type: DTF Bundle':'Product files ready for review'}</span></div><small>{summary.files.length} supported · {summary.ignored} ignored{summary.archiveCount?` · ${summary.archiveCount} ZIP`:''}</small></div>}
    {ordered.length>0&&<div className="file-review"><div className="review-head"><div><span>FILE REVIEW</span><h3>{ordered.filter(file=>file.type.startsWith('image/')).length} product image{ordered.filter(file=>file.type.startsWith('image/')).length===1?'':'s'} ready</h3></div><div><button className="secondary" onClick={()=>setSelected(new Set(ordered.map(file=>file.id)))}>Select all</button><button className="secondary danger" disabled={!selected.size} onClick={removeSelected}><Trash2/> Remove selected</button></div></div><div className="review-list">{ordered.map((file,index)=><article key={file.id} className={file.primary?'primary-file':''}><label className="select-file"><input type="checkbox" checked={selected.has(file.id)} onChange={e=>setSelected(current=>{const next=new Set(current);e.target.checked?next.add(file.id):next.delete(file.id);return next})}/></label>{file.dataUrl&&file.type.startsWith('image/')?<img src={file.dataUrl}/>:<div className="file-icon">{file.type.includes('zip')?<FileArchive/>:<ImageIcon/>}</div>}<div className="review-file-copy"><b>{file.name}</b><small>{file.width&&file.height?`${file.width} × ${file.height} · `:''}{file.type.split('/').pop()?.toUpperCase()} · {fileSize(file.size)}</small><em>{file.relativePath}</em></div>{file.primary?<span className="primary-design"><Star/> Primary design</span>:file.type.startsWith('image/')&&<button className="text-btn" onClick={()=>setPrimary(file.id)}><Star/> Set primary</button>}<div className="review-actions"><button title="Move up" disabled={index===0} onClick={()=>move(file.id,-1)}><ArrowUp/></button><button title="Move down" disabled={index===ordered.length-1} onClick={()=>move(file.id,1)}><ArrowDown/></button><button title="Remove file" onClick={()=>remove(file.id)}><Trash2/></button></div></article>)}</div>{onContinue&&<button className="primary continue-mockups" onClick={onContinue}>Continue to Mockup Studio <ArrowRight/></button>}</div>}
  </div>
}
