import {useMemo,useState} from 'react';
import JSZip from 'jszip';
import {ArrowDownToLine,Check,CircleAlert,Crown,Download,GalleryHorizontalEnd,Image as ImageIcon,LoaderCircle,MoveLeft,MoveRight,RefreshCcw,Sparkles,Star,Trash2} from 'lucide-react';
import type {Project,Mockup} from './types';
import {download} from './lib';
import {generateMarketplaceGallery,regenerateGalleryImage,type GalleryDirection,type GalleryKind} from './mockupEngine';

const directions:Array<{id:GalleryDirection;name:string;note:string}>=[
  {id:'auto',name:'Smart direction',note:'SHOPMINT selects for product type'},
  {id:'luxury-editorial',name:'Luxury editorial',note:'Ink, cream and sculptural styling'},
  {id:'trendy-boutique',name:'Trendy boutique',note:'Warm, polished and contemporary'},
  {id:'colorful-studio',name:'Colorful studio',note:'Bright maker energy and dimension'},
  {id:'clean-premium',name:'Clean premium',note:'Quiet, refined merchandising'},
  {id:'feminine-glam',name:'Feminine glam',note:'Soft contrast and luxe accents'},
  {id:'bold-streetwear',name:'Bold streetwear',note:'High contrast apparel campaign'},
  {id:'seasonal',name:'Seasonal',note:'Rich holiday-ready presentation'}
];
const sceneRoot=`${import.meta.env.BASE_URL}assets/mockup-scenes/`;
const scenes={tee:`${sceneRoot}luxury-tee.png`,sweatshirt:`${sceneRoot}streetwear-sweatshirt.png`,flatlay:`${sceneRoot}creative-flatlay.png`};
const blob=(url:string)=>{const [meta,data]=url.split(',');const raw=atob(data),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return new Blob([bytes],{type:meta.match(/:(.*?);/)?.[1]||'image/png'})};
const slug=(s:string)=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');

export default function MockupStudio({project,update,notify}:{project:Project;update:(f:(p:Project)=>Project)=>void;notify:(s:string)=>void}){
  const [direction,setDirection]=useState<GalleryDirection>('auto');const [generating,setGenerating]=useState(false);const [progress,setProgress]=useState('');const [active,setActive]=useState<string>();const [watermark,setWatermark]=useState(true);const [watermarkText,setWatermarkText]=useState('PREVIEW');const [opacity,setOpacity]=useState(16);
  const art=project.sourceFiles.filter(f=>f.dataUrl&&f.type.startsWith('image/'));const gallery=useMemo(()=>project.mockups.filter(m=>m.kind).sort((a,b)=>(a.order||0)-(b.order||0)),[project.mockups]);const selected=gallery.find(m=>m.id===active)||gallery.find(m=>m.primary)||gallery[0];
  const opts=()=>({productName:project.productName,productType:project.productType,files:project.sourceFiles,direction,watermark:{enabled:watermark,text:watermarkText,opacity},scenes,onProgress:setProgress});
  const generate=async()=>{setGenerating(true);try{const items=await generateMarketplaceGallery(opts());update(p=>({...p,mockups:[...items,...p.mockups.filter(m=>!m.kind)]}));setActive(items[0].id);notify('Complete 7-image marketplace gallery created')}catch(e){notify(e instanceof Error?e.message:'Could not build the gallery')}finally{setGenerating(false);setProgress('')}};
  const setPrimary=(id:string)=>update(p=>({...p,mockups:p.mockups.map(m=>m.kind?{...m,primary:m.id===id}:m)}));
  const remove=(id:string)=>update(p=>{const rest=p.mockups.filter(m=>m.id!==id);if(!rest.some(m=>m.kind&&m.primary)){const first=rest.find(m=>m.kind);if(first)first.primary=true}return{...p,mockups:rest}});
  const move=(id:string,delta:number)=>update(p=>{const kinds=p.mockups.filter(m=>m.kind).sort((a,b)=>(a.order||0)-(b.order||0));const index=kinds.findIndex(m=>m.id===id),next=Math.max(0,Math.min(kinds.length-1,index+delta));if(index===next)return p;[kinds[index],kinds[next]]=[kinds[next],kinds[index]];const order=new Map(kinds.map((m,i)=>[m.id,i]));return{...p,mockups:p.mockups.map(m=>m.kind?{...m,order:order.get(m.id)}:m)}});
  const replace=async(m:Mockup)=>{if(!m.kind)return;setGenerating(true);setProgress(`Refreshing ${m.kind.replace(/-/g,' ')}`);try{const dataUrl=await regenerateGalleryImage(m.kind as GalleryKind,opts());update(p=>({...p,mockups:p.mockups.map(x=>x.id===m.id?{...x,dataUrl,style:direction==='auto'?'smart direction':direction,createdAt:new Date().toISOString()}:x)}));notify('Supporting scene replaced')}finally{setGenerating(false);setProgress('')}};
  const exportAll=async()=>{const zip=new JSZip();gallery.forEach((m,i)=>zip.file(`${String(i+1).padStart(2,'0')}-${slug(m.kind||m.name)}.png`,m.dataUrl.split(',')[1],{base64:true}));download(`${slug(project.productName)}-listing-gallery.zip`,await zip.generateAsync({type:'blob'}));notify('Listing gallery ZIP exported')};
  return <section className="panel gallery-studio"><div className="panel-head"><div><div className="eyebrow"><Sparkles/> MARKETPLACE GALLERY ENGINE</div><h2>Merchandise the collection.</h2><p>Generate a coordinated seven-image listing story. Uploaded artwork is composited as an untouched source layer—never regenerated.</p></div><div className="source-badge"><b>{art.length}</b><span>artwork file{art.length===1?'':'s'}</span></div></div>
    {!art.length?<div className="gallery-empty"><ImageIcon/><h3>Add your bundle artwork first.</h3><p>Upload each design as a separate PNG in Product Files. SHOPMINT will sell the collection, not flatten it into one generic preview.</p></div>:<>
    <div className="direction-head"><div><span>01 / ART DIRECTION</span><h3>Choose the campaign mood</h3></div><small>Auto selects bold streetwear for DTF products.</small></div><div className="direction-grid">{directions.map(d=><button key={d.id} className={direction===d.id?'active':''} onClick={()=>setDirection(d.id)}><span>{d.id==='auto'?<Sparkles/>:<Crown/>}</span><b>{d.name}</b><small>{d.note}</small>{direction===d.id&&<Check/>}</button>)}</div>
    <div className="generation-bar"><div><label className="switch"><input type="checkbox" checked={watermark} onChange={e=>setWatermark(e.target.checked)}/><span></span> Preview watermark</label>{watermark&&<div className="watermark-inline"><input aria-label="Watermark text" value={watermarkText} onChange={e=>setWatermarkText(e.target.value)} placeholder="PREVIEW"/><label>Opacity <input type="range" min="5" max="45" value={opacity} onChange={e=>setOpacity(+e.target.value)}/></label></div>}</div><button className="primary generate-gallery" disabled={generating} onClick={generate}>{generating?<><LoaderCircle className="spin"/>{progress}</>:<><GalleryHorizontalEnd/>Generate 7-image listing set</>}</button></div>
    {gallery.length>0&&<><div className="gallery-workspace"><div className="gallery-preview">{selected&&<img src={selected.dataUrl}/>}<div className="preview-top"><span>{selected?.primary?'PRIMARY THUMBNAIL':'LISTING IMAGE'}</span><b>{selected?.name}</b></div><div className="preview-bottom"><button onClick={()=>selected&&download(`${slug(project.productName)}-${slug(selected.kind||'mockup')}.png`,blob(selected.dataUrl),'image/png')}><Download/> Export image</button><button onClick={exportAll}><ArrowDownToLine/> Export all 7</button></div></div><aside className="gallery-story"><span>02 / LISTING STORY</span><h3>A complete buyer journey</h3><p>Lead with the bundle, prove the variety, show it in use, then answer purchase questions before buyers ask.</p><div className="story-checks">{['Collection is obvious','Artwork stays unchanged','Apparel context included','File details are clear','Download steps included'].map(x=><div key={x}><Check/>{x}</div>)}</div><div className="integrity"><CircleAlert/><span><b>Artwork integrity lock</b>All source files are fitted proportionally. No redraw, recolor, stretch, or generative editing is applied.</span></div></aside></div>
    <div className="listing-gallery"><div className="gallery-title"><div><span>03 / GALLERY ORDER</span><h3>Arrange the marketplace sequence</h3></div><p>Tap any card to preview. Set the strongest image as the primary thumbnail.</p></div><div className="gallery-cards">{gallery.map((m,i)=><article key={m.id} className={`${selected?.id===m.id?'selected':''} ${m.primary?'primary-card':''}`} onClick={()=>setActive(m.id)}><div className="gallery-card-img"><img src={m.dataUrl}/><b>{String(i+1).padStart(2,'0')}</b>{m.primary&&<span><Star/> PRIMARY</span>}</div><h4>{m.kind?.replace(/-/g,' ')}</h4><div className="gallery-card-actions"><button title="Move earlier" disabled={i===0} onClick={e=>{e.stopPropagation();move(m.id,-1)}}><MoveLeft/></button><button title="Move later" disabled={i===gallery.length-1} onClick={e=>{e.stopPropagation();move(m.id,1)}}><MoveRight/></button><button title="Replace scene" onClick={e=>{e.stopPropagation();replace(m)}}><RefreshCcw/></button><button title="Remove" onClick={e=>{e.stopPropagation();remove(m.id)}}><Trash2/></button></div>{!m.primary&&<button className="make-primary" onClick={e=>{e.stopPropagation();setPrimary(m.id)}}><Star/> Make primary</button>}</article>)}</div></div></>}
    </>}</section>
}
